// Praxys Web — real photography visual system
(function(){
  const WHATSAPP='https://wa.me/5492944770005?text=Hola%20Praxys%2C%20quisiera%20agendar%20una%20conversaci%C3%B3n%20ejecutiva%20sobre%20un%20problema%20que%20cruza%20%C3%A1reas.';
  const U=(id,w=1200)=>`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=78`;
  const PHOTOS={
    hero:U('1557804506-669a67965ba0',1800),
    pRisk:U('1513828583688-c52646db42da'),
    pPriority:U('1551434678-e076c223a692'),
    pRecurrence:U('1581091226825-a6a2a5aee158'),
    svcDiagnosis:U('1559136555-9303baea8ebd'),
    svcPriority:U('1542744173-8e7e53415bb0'),
    svcScenario:U('1543286386-713bdd548da4'),
    svcRecurrence:U('1504917595217-d4dc5ebe6122'),
    svcGovernance:U('1497366754035-f200968a6e72'),
    svcTraining:U('1521737604893-d14cc237f11d'),
    c1:U('1517048676732-d65bc937f952'),
    c2:U('1568992687947-868a62a9f521'),
    c3:U('1454165804606-c3d57bc86b40'),
    c4:U('1581092160607-ee22621dd758'),
    c5:U('1556761175-b413da4baf72'),
    c6:U('1552664730-d307ca884978')
  };

  const SERVICES=[
    {id:'diagnosis',photo:PHOTOS.svcDiagnosis,es:{title:'Diagnóstico ejecutivo de riesgos combinados',line:'Ordena causas, dependencias y efectos cuando el problema cruza áreas.',receive:'Mapa causal, prioridades de intervención y criterios de seguimiento.',detail:'Integramos datos, eventos, restricciones y criterios de distintas áreas para construir una lectura común del problema y orientar decisiones concretas.'},en:{title:'Executive diagnosis of combined risks',line:'Structures causes, dependencies, and effects when the problem crosses areas.',receive:'Causal map, intervention priorities, and follow-up criteria.',detail:'We integrate data, events, constraints, and criteria from different areas to build a shared reading of the problem and guide concrete decisions.'}},
    {id:'prioritization',photo:PHOTOS.svcPriority,es:{title:'Priorización de acciones y recursos',line:'Convierte carteras extensas en una secuencia ejecutable con recursos limitados.',receive:'Matriz de priorización, responsables y condiciones de implementación.',detail:'Ayudamos a decidir qué acciones ejecutar primero, cuáles agrupar, cuáles postergar y qué riesgos quedan aceptados temporalmente.'},en:{title:'Prioritization of actions and resources',line:'Turns extensive action portfolios into an executable sequence under limited resources.',receive:'Prioritization matrix, owners, and implementation conditions.',detail:'We help decide what goes first, what can be grouped, what waits, and which risks are temporarily accepted.'}},
    {id:'scenarios',photo:PHOTOS.svcScenario,es:{title:'Evaluación de escenarios de decisión',line:'Compara alternativas antes de comprometer inversión, recursos o cambios operativos.',receive:'Escenarios comparados, trade-offs, riesgos residuales y recomendación.',detail:'Estructuramos escenarios comparables, explicitamos supuestos y analizamos consecuencias sobre continuidad, costos, riesgo residual y capacidad de seguimiento.'},en:{title:'Decision scenario assessment',line:'Compares alternatives before committing investment, resources, or operational changes.',receive:'Compared scenarios, trade-offs, residual risks, and recommendation.',detail:'We structure comparable scenarios, make assumptions explicit, and analyze consequences on continuity, costs, residual risk, and follow-up capability.'}},
    {id:'recurrence',photo:PHOTOS.svcRecurrence,es:{title:'Investigación sistémica de eventos recurrentes',line:'Identifica por qué fallas o incidentes vuelven aunque existan acciones correctivas.',receive:'Línea de tiempo, barreras degradadas, mapa causal y acciones de mayor impacto.',detail:'Reconstruimos eventos, decisiones, barreras, señales, presiones y responsabilidades para separar causas inmediatas de condiciones que sostienen la recurrencia.'},en:{title:'Systemic investigation of recurring events',line:'Identifies why failures or incidents reappear despite corrective actions.',receive:'Timeline, degraded barriers, causal map, and higher-impact actions.',detail:'We reconstruct events, decisions, barriers, signals, pressures, and responsibilities to separate immediate causes from conditions that sustain recurrence.'}},
    {id:'governance',photo:PHOTOS.svcGovernance,es:{title:'Diseño de gobernanza y seguimiento',line:'Hace que decisiones aprobadas tengan responsables, indicadores y reglas de escalamiento.',receive:'Tablero ejecutivo, rutina de revisión, roles y reglas de escalamiento.',detail:'Diseñamos mecanismos de seguimiento para que una decisión no se diluya entre áreas y pueda verificarse con indicadores, responsables y reglas claras.'},en:{title:'Governance and follow-up design',line:'Gives approved decisions owners, indicators, and escalation rules.',receive:'Executive dashboard, review routine, roles, and escalation rules.',detail:'We design follow-up mechanisms so decisions do not dilute across areas and can be verified through indicators, owners, and clear rules.'}},
    {id:'training',photo:PHOTOS.svcTraining,es:{title:'Capacitación ejecutiva y transferencia metodológica',line:'Instala criterios comunes para analizar problemas reales y decidir entre áreas.',receive:'Workshops aplicados, plantillas y herramientas transferibles.',detail:'Trabajamos sobre casos reales del cliente para transferir criterios, plantillas y rutinas que queden instaladas en el equipo.'},en:{title:'Executive training and method transfer',line:'Installs shared criteria to analyze real problems and decide across areas.',receive:'Applied workshops, templates, and transferable tools.',detail:'We work on the client’s real cases to transfer criteria, templates, and routines that remain installed in the team.'}}
  ];

  const PROBLEMS={es:[
    {photo:PHOTOS.pRisk,title:'El riesgo se propaga entre áreas',text:'Un cambio o falla local termina afectando recursos, continuidad, costos o decisiones de dirección.'},
    {photo:PHOTOS.pPriority,title:'Las prioridades compiten por los mismos recursos',text:'Todo parece importante, pero no todo puede ejecutarse al mismo tiempo ni con la misma capacidad.'},
    {photo:PHOTOS.pRecurrence,title:'Los problemas vuelven aunque se cierren acciones',text:'Las soluciones puntuales no modifican las condiciones que reproducen el patrón.'}
  ],en:[
    {photo:PHOTOS.pRisk,title:'Risk propagates across areas',text:'A local change or failure ends up affecting resources, continuity, costs, or leadership decisions.'},
    {photo:PHOTOS.pPriority,title:'Priorities compete for the same resources',text:'Everything seems important, but not everything can be executed at the same time or with the same capacity.'},
    {photo:PHOTOS.pRecurrence,title:'Problems return after actions are closed',text:'Local fixes do not change the conditions that reproduce the pattern.'}
  ]};

  const CASES=[
    {id:'diagnosis',photo:PHOTOS.c1,es:{label:'Caso 01',title:'Cada área explica una causa distinta del mismo problema',situation:'Las áreas interpretan la situación desde evidencia, responsabilidades y restricciones diferentes.',decision:'Construir una lectura común y decidir dónde intervenir primero.',deliver:['Mapa causal','Dependencias críticas','Prioridades'],work:'Praxys reconstruye eventos, datos, decisiones previas y restricciones para distinguir causas inmediatas, condiciones sistémicas y puntos de intervención.'},en:{label:'Case 01',title:'Each area explains a different cause of the same problem',situation:'Areas interpret the situation from different evidence, responsibilities, and constraints.',decision:'Build a shared reading and decide where to intervene first.',deliver:['Causal map','Critical dependencies','Priorities'],work:'Praxys reconstructs events, data, previous decisions, and constraints to distinguish immediate causes, systemic conditions, and intervention points.'}},
    {id:'prioritization',photo:PHOTOS.c2,es:{label:'Caso 02',title:'Hay demasiadas acciones abiertas para la capacidad disponible',situation:'Las acciones compiten por personas, presupuesto, tiempo y capacidad de gestión.',decision:'Ordenar qué ejecutar primero, qué agrupar y qué postergar.',deliver:['Matriz de priorización','Secuencia ejecutable','Responsables'],work:'Praxys releva acciones, restricciones, impacto esperado, dependencias y responsables para construir una secuencia realista de implementación.'},en:{label:'Case 02',title:'Too many actions are open for available capacity',situation:'Actions compete for people, budget, time, and management capacity.',decision:'Decide what goes first, what can be grouped, and what waits.',deliver:['Prioritization matrix','Executable sequence','Owners'],work:'Praxys reviews actions, constraints, expected impact, dependencies, and owners to build a realistic implementation sequence.'}},
    {id:'scenarios',photo:PHOTOS.c3,es:{label:'Caso 03',title:'La inversión requiere comparar escenarios, costos y riesgos',situation:'La dirección debe comprometer recursos relevantes y necesita comparar impactos, supuestos y riesgos residuales con criterios explícitos.',decision:'Comparar alternativas con los mismos criterios y elegir una opción defendible.',deliver:['Escenarios comparados','Trade-offs','Supuestos críticos'],work:'Praxys define escenarios comparables, explicita supuestos y analiza consecuencias sobre continuidad, disponibilidad, costos, riesgo residual y capacidad de seguimiento.'},en:{label:'Case 03',title:'Investment requires comparing scenarios, costs, and risks',situation:'Leadership must commit relevant resources and compare impacts, assumptions, and residual risks through explicit criteria.',decision:'Compare alternatives with the same criteria and choose a defensible option.',deliver:['Compared scenarios','Trade-offs','Critical assumptions'],work:'Praxys defines comparable scenarios, makes assumptions explicit, and analyzes consequences on continuity, availability, costs, residual risk, and follow-up capability.'}},
    {id:'recurrence',photo:PHOTOS.c4,es:{label:'Caso 04',title:'Las acciones se cierran, pero los incidentes vuelven',situation:'Los reportes muestran eventos cerrados, pero el patrón reaparece en la operación real.',decision:'Determinar qué condiciones sostienen la recurrencia y qué intervención tiene mayor efecto.',deliver:['Línea de tiempo','Barreras degradadas','Mapa causal'],work:'Praxys reconstruye la secuencia de eventos, decisiones, barreras, señales, presiones, demoras y responsabilidades para separar síntomas de condiciones sistémicas.'},en:{label:'Case 04',title:'Actions are closed, but incidents keep coming back',situation:'Reports show closed events, but the pattern reappears in real operation.',decision:'Determine which conditions sustain recurrence and which intervention has the highest effect.',deliver:['Timeline','Degraded barriers','Causal map'],work:'Praxys reconstructs event sequences, decisions, barriers, signals, pressures, delays, and responsibilities to separate symptoms from systemic conditions.'}},
    {id:'governance',photo:PHOTOS.c5,es:{label:'Caso 05',title:'La decisión está aprobada, pero el seguimiento se diluye',situation:'La ejecución queda repartida sin suficiente claridad sobre responsabilidades, indicadores y escalamiento.',decision:'Definir cómo se gobierna la decisión y cuándo deben escalarse los desvíos.',deliver:['Modelo de gobernanza','Tablero ejecutivo','Roles'],work:'Praxys diseña un mecanismo de seguimiento con tablero, frecuencia de revisión, responsables y reglas de escalamiento.'},en:{label:'Case 05',title:'The decision is approved, but follow-up dilutes',situation:'Execution is distributed without enough clarity on responsibilities, indicators, and escalation.',decision:'Define how the decision is governed and when deviations must be escalated.',deliver:['Governance model','Executive dashboard','Roles'],work:'Praxys designs a follow-up mechanism with dashboard, review frequency, owners, and escalation rules.'}},
    {id:'training',photo:PHOTOS.c6,es:{label:'Caso 06',title:'Los equipos analizan el problema con criterios distintos',situation:'Áreas técnicas, operación y gerencias discuten con lenguajes y criterios diferentes.',decision:'Instalar una forma común de analizar, priorizar y sostener decisiones.',deliver:['Workshops aplicados','Guías','Plantillas'],work:'Praxys trabaja sobre casos reales para transferir criterios, plantillas y rutinas que queden instaladas en el equipo.'},en:{label:'Case 06',title:'Teams analyze the problem with different criteria',situation:'Technical areas, operations, and management discuss with different language and criteria.',decision:'Install a shared way to analyze, prioritize, and sustain decisions.',deliver:['Applied workshops','Guides','Templates'],work:'Praxys works on real cases to transfer criteria, templates, and routines that remain installed in the team.'}}
  ];

  const PAPERS=[
    ['2020','Revisión post-Fukushima','Gestión de la seguridad nuclear después de Fukushima','Revisión crítica del estado del arte sobre gestión de seguridad, factores organizacionales y aprendizaje post-accidente.'],
    ['2021','Modelado jerárquico','Modelado funcional de reactores nucleares','Aplicación combinada de GTST-DMLD y dinámica de sistemas para evaluar seguridad, disponibilidad y escenarios de falla.'],
    ['2021','Dinámica de sistemas','Marco para modelar gestión de seguridad','Propuesta conceptual para integrar decisiones, acciones humanas, tecnología y entorno en la gestión de seguridad.'],
    ['2023','ESREL','Modelo causal detallado de gestión de seguridad','Modelo basado en dinámica de sistemas para estudiar seguridad, disponibilidad y trade-offs operacionales.'],
    ['2023','ISDC','Modelo conceptual HTOE/MTOE','Integración de factores humanos, tecnológicos, organizacionales y ambientales en organizaciones complejas.'],
    ['2025','BJRS','Modelo cuantitativo de cultura de seguridad','Simulación de cultura de seguridad, liderazgo, comunicación, mejora continua y desempeño operacional.']
  ];

  function lang(){return (localStorage.getItem('selectedLanguage')||document.documentElement.lang||'es')==='en'?'en':'es'}
  function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function photo(src,alt){return `<figure class="photo"><img src="${esc(src)}" alt="${esc(alt)}" loading="lazy" decoding="async"></figure>`}
  function sectionHead(k,h,p){return `<div class="section-head"><span class="eyebrow">${esc(k)}</span><h2>${esc(h)}</h2><p>${esc(p)}</p></div>`}
  function setHTML(id,html,cls='site-section'){const el=document.getElementById(id);if(el){el.className=cls;el.innerHTML=html}return el}

  function installStyles(){
    let s=document.getElementById('praxys-real-photo-styles');
    if(!s){s=document.createElement('style');s.id='praxys-real-photo-styles';document.head.appendChild(s)}
    s.textContent=`
      :root{--navy:#102033;--blue:#17365d;--text:#25384d;--muted:#5d6e82;--line:rgba(16,32,51,.12);--bg:#f5f8fb;--orange:#E8632A;--amber:#F2C94C;--radius:24px;--shadow:0 18px 48px rgba(16,32,51,.08)}
      body{background:#fff;color:var(--text);font-family:Inter,Manrope,Segoe UI,Arial,sans-serif;line-height:1.55}.wrap{width:min(1160px,calc(100% - 44px));margin:0 auto}.navbar{background:rgba(255,255,255,.96)!important;border-bottom:1px solid var(--line)!important;box-shadow:0 8px 26px rgba(16,32,51,.05)!important}.nav-menu a{color:var(--text)!important}.nav-menu a:hover{color:var(--orange)!important}.lang-btn.active{background:var(--navy)!important;color:#fff!important}
      .hero-real{position:relative;min-height:620px;display:flex;align-items:center;color:#fff;background-image:linear-gradient(90deg,rgba(16,32,51,.88) 0%,rgba(16,32,51,.72) 42%,rgba(16,32,51,.20) 100%),url('${PHOTOS.hero}');background-size:cover;background-position:center center}.hero-real .wrap{padding:104px 0}.hero-copy{max-width:760px}.eyebrow{display:inline-block;color:var(--orange);font-size:.76rem;letter-spacing:.16em;text-transform:uppercase;font-weight:950}.hero-real .eyebrow{color:var(--amber)}.hero-real h1{margin:14px 0 18px;font-size:clamp(2.7rem,5.6vw,5.1rem);line-height:.98;letter-spacing:-.05em;color:#fff;text-wrap:balance}.hero-real p{max-width:720px;color:#e1edf8;font-size:clamp(1.08rem,1.55vw,1.28rem);line-height:1.62;font-weight:520}.hero-actions{display:flex;gap:14px;flex-wrap:wrap;margin-top:28px}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 22px;border-radius:999px;text-decoration:none;font-weight:950;text-transform:uppercase;font-size:.78rem;letter-spacing:.05em}.btn.orange{background:var(--orange);color:#fff}.btn.dark{background:var(--navy);color:#fff}.btn.line{border:1px solid var(--line);color:var(--navy);background:#fff}
      .site-section{padding:74px 0}.site-section.light{background:#fff}.site-section.soft{background:var(--bg)}.section-head{text-align:center;max-width:820px;margin:0 auto 34px}.section-head h2{margin:8px 0 10px;color:var(--navy);font-size:clamp(2rem,3.45vw,3.15rem);line-height:1.05;letter-spacing:-.04em;text-wrap:balance}.section-head p{margin:0;color:var(--muted);font-size:1.08rem;line-height:1.65}.grid{display:grid;gap:22px}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.card{background:#fff;border:1px solid var(--line);border-radius:var(--radius);overflow:hidden;box-shadow:var(--shadow)}.photo{margin:0;aspect-ratio:16/9;overflow:hidden;background:#e8eef5}.photo img{width:100%;height:100%;display:block;object-fit:cover;filter:saturate(.96) contrast(1.02)}.body{padding:22px;display:flex;flex-direction:column;gap:12px}.kicker{color:var(--orange);font-size:.72rem;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.card h3{margin:0;color:var(--navy);font-size:1.24rem;line-height:1.22;letter-spacing:-.02em}.card p{margin:0;color:var(--muted);font-size:1rem;line-height:1.58}.receive{padding:14px;border:1px solid var(--line);border-radius:16px;background:#f7fafc}.receive strong{display:block;color:var(--orange);font-size:.7rem;letter-spacing:.11em;text-transform:uppercase;margin-bottom:5px}.receive span{color:var(--text);font-weight:750;font-size:.94rem;line-height:1.42}.card .btn{margin-top:auto}.cta-band{padding:36px 0;background:linear-gradient(135deg,#102033,#17365d);color:#fff}.cta-inner{display:flex;align-items:center;justify-content:space-between;gap:28px}.cta-inner h2{margin:6px 0;color:#fff;font-size:clamp(1.6rem,2.7vw,2.3rem)}.cta-inner p{margin:0;color:#d4e1ef;max-width:720px}
      .case-card .photo{aspect-ratio:16/8.6}.case-card h3{font-size:1.34rem}.mini{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mini p{padding:13px;border:1px solid var(--line);border-radius:16px;background:#fbfdff}.mini strong{display:block;color:var(--orange);font-size:.7rem;letter-spacing:.1em;text-transform:uppercase;margin-bottom:5px}.chips{display:flex;flex-wrap:wrap;gap:7px}.chips span{border-radius:999px;background:rgba(232,99,42,.10);color:#A9461D;padding:6px 10px;font-size:.78rem;font-weight:850}.method-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.method-card{padding:24px}.method-card .n{width:38px;height:38px;border-radius:999px;background:var(--orange);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:950;margin-bottom:16px}.paper-controls{display:flex;justify-content:flex-end;align-items:center;gap:10px;margin:0 0 18px}.paper-controls button{width:42px;height:42px;border:0;border-radius:999px;background:var(--navy);color:#fff;font-weight:950;cursor:pointer}.paper-controls button:hover{background:var(--orange)}.paper-count{font-size:.86rem;font-weight:950;color:var(--navy);min-width:62px;text-align:center}.paper-reel{display:flex;gap:22px;overflow-x:auto;scroll-snap-type:x mandatory;scroll-behavior:smooth;padding:2px 2px 14px;scrollbar-width:none}.paper-reel::-webkit-scrollbar{display:none}.paper{flex:0 0 calc((100% - 44px)/3);scroll-snap-align:start;min-height:292px}.paper .body{height:100%}.paper h3{font-size:1.18rem}.paper a{margin-top:auto;color:var(--orange);font-weight:900;text-decoration:none}.contact-box{text-align:center;max-width:740px;margin:0 auto}.contact-box p{color:var(--muted);font-size:1.02rem}.modal{position:fixed;inset:0;z-index:9999;background:rgba(4,10,18,.65);display:none;align-items:center;justify-content:center;padding:24px}.modal.open{display:flex}.modal-box{background:#fff;border-radius:28px;max-width:980px;width:100%;max-height:88vh;overflow:auto;box-shadow:0 36px 100px rgba(0,0,0,.35)}.modal-box .photo{border-radius:28px 28px 0 0}.modal-content{padding:30px}.close{position:absolute;right:20px;top:20px;border:0;background:var(--navy);color:#fff;border-radius:999px;width:40px;height:40px;font-size:1.4rem;cursor:pointer}.modal h2{color:var(--navy);font-size:clamp(1.7rem,3vw,2.55rem);line-height:1.08;margin:8px 46px 12px 0}.modal h4{color:var(--orange);font-size:.76rem;letter-spacing:.12em;text-transform:uppercase;margin:18px 0 6px}.lock{overflow:hidden}
      @media(max-width:1050px){.grid.three{grid-template-columns:repeat(2,minmax(0,1fr))}.grid.two{grid-template-columns:1fr}.method-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.paper{flex-basis:calc((100% - 22px)/2)}}
      @media(max-width:720px){.wrap{width:min(100% - 30px,1160px)}.hero-real{min-height:560px;background-position:center center}.hero-real .wrap{padding:74px 0}.hero-real h1{font-size:clamp(2.35rem,12vw,3.5rem)}.site-section{padding:56px 0}.section-head{text-align:left;margin-bottom:26px}.grid.three,.method-grid{grid-template-columns:1fr}.mini{grid-template-columns:1fr}.cta-inner{display:block}.cta-inner .btn{margin-top:20px}.paper{flex-basis:88%}.paper-controls{justify-content:center}.modal-content{padding:24px}}
    `;
  }

  function renderHero(l){setHTML('inicio',`<div class="wrap"><div class="hero-copy"><span class="eyebrow">Integral Risk Consulting</span><h1>${l==='en'?'Executive decisions for problems that cross areas':'Decisiones ejecutivas para problemas que cruzan áreas'}</h1><p>${l==='en'?'Praxys structures evidence, models relationships, prioritizes alternatives, and helps sustain decisions in complex systems.':'Praxys ordena evidencia, modela relaciones, prioriza alternativas y ayuda a sostener decisiones en sistemas complejos.'}</p><div class="hero-actions"><a class="btn orange" href="${WHATSAPP}" target="_blank" rel="noopener">${l==='en'?'Schedule conversation':'Agendar conversación'}</a><a class="btn dark" href="#casos-concretos">${l==='en'?'View cases':'Ver casos'}</a></div></div></div>`,'hero-real')}
  function renderProblems(l){setHTML('problemas',`<div class="wrap">${sectionHead(l==='en'?'Management problems':'Problemas de gestión',l==='en'?'Problems that block management decisions':'Problemas que traban decisiones de gestión',l==='en'?'Recurring situations where evidence, areas, resources, and follow-up become misaligned.':'Situaciones recurrentes donde evidencia, áreas, recursos y seguimiento quedan desalineados.')}<div class="grid three">${PROBLEMS[l].map(p=>`<article class="card">${photo(p.photo,p.title)}<div class="body"><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p></div></article>`).join('')}</div></div>`,'site-section soft')}
  function renderServices(l){setHTML('servicios',`<div class="wrap">${sectionHead(l==='en'?'Services':'Servicios',l==='en'?'Services designed around decisions':'Servicios diseñados alrededor de decisiones',l==='en'?'Each service is a focused intervention with a concrete executive output.':'Cada servicio es una intervención acotada con un resultado ejecutivo concreto.')}<div class="grid three">${SERVICES.map(s=>{const t=s[l];return `<article class="card">${photo(s.photo,t.title)}<div class="body"><span class="kicker">${l==='en'?'Service':'Servicio'}</span><h3>${esc(t.title)}</h3><p>${esc(t.line)}</p><div class="receive"><strong>${l==='en'?'Leadership receives':'La dirección recibe'}</strong><span>${esc(t.receive)}</span></div><button class="btn dark" data-open-service="${s.id}">${l==='en'?'View detail':'Ver detalle'}</button></div></article>`}).join('')}</div></div>`,'site-section light')}
  function renderCTA(l){let old=document.getElementById('praxys-mid-cta'); if(old) old.remove(); const sec=document.createElement('section');sec.id='praxys-mid-cta';sec.className='cta-band';sec.innerHTML=`<div class="wrap cta-inner"><div><span class="eyebrow">${l==='en'?'Focused start':'Inicio enfocado'}</span><h2>${l==='en'?'A short conversation is enough to frame the decision':'Una conversación breve alcanza para encuadrar la decisión'}</h2><p>${l==='en'?'We identify the decision, involved areas, available evidence, and the most useful deliverable.':'Identificamos la decisión, las áreas involucradas, la evidencia disponible y el entregable más útil.'}</p></div><a class="btn orange" href="${WHATSAPP}" target="_blank" rel="noopener">${l==='en'?'Schedule':'Agendar'}</a></div>`;document.getElementById('servicios')?.after(sec)}
  function renderCases(l){setHTML('casos-concretos',`<div class="wrap">${sectionHead(l==='en'?'Concrete cases':'Casos concretos',l==='en'?'Problems where Praxys helps decide and move forward':'Problemas donde Praxys ayuda a decidir y avanzar',l==='en'?'Brief, readable examples. Detail opens only when needed.':'Ejemplos breves y legibles. El detalle se abre solo cuando hace falta.')}<div class="grid two">${CASES.map(c=>{const t=c[l];return `<article class="card case-card" id="case-${c.id}">${photo(c.photo,t.title)}<div class="body"><span class="kicker">${esc(t.label)}</span><h3>${esc(t.title)}</h3><div class="mini"><p><strong>${l==='en'?'Situation':'Situación'}</strong>${esc(t.situation)}</p><p><strong>${l==='en'?'Decision':'Decisión'}</strong>${esc(t.decision)}</p></div><div class="chips">${t.deliver.map(x=>`<span>${esc(x)}</span>`).join('')}</div><button class="btn dark" data-open-case="${c.id}">${l==='en'?'View case detail':'Ver detalle del caso'}</button></div></article>`}).join('')}</div></div>`,'site-section soft')}
  function renderMethod(l){const steps=l==='en'?[['01','Frame','Define the decision and boundaries.'],['02','Integrate','Connect evidence, constraints, and areas.'],['03','Prioritize','Compare scenarios, actions, and trade-offs.'],['04','Sustain','Assign owners, indicators, and follow-up rules.']]:[['01','Encuadrar','Definir la decisión y sus límites.'],['02','Integrar','Conectar evidencia, restricciones y áreas.'],['03','Priorizar','Comparar escenarios, acciones y trade-offs.'],['04','Sostener','Asignar responsables, indicadores y reglas de seguimiento.']];setHTML('metodo',`<div class="wrap">${sectionHead(l==='en'?'Method':'Método',l==='en'?'How Praxys works':'Cómo trabaja Praxys',l==='en'?'A compact path from scattered information to governed decisions.':'Un recorrido compacto desde información dispersa hacia decisiones gobernadas.')}<div class="grid method-grid">${steps.map(x=>`<article class="card method-card"><div class="n">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></div>`,'site-section light')}
  function renderPapers(l){setHTML('articulos',`<div class="wrap">${sectionHead(l==='en'?'Publications':'Publicaciones',l==='en'?'Technical authority behind the method':'Autoridad técnica detrás del método',l==='en'?'Selected publications supporting the systemic approach.':'Publicaciones seleccionadas que respaldan el enfoque sistémico.')}<div class="paper-controls"><button data-paper-prev>←</button><span class="paper-count"><b>1</b> / <em>1</em></span><button data-paper-next>→</button></div><div class="paper-reel">${PAPERS.map(p=>`<article class="card paper"><div class="body"><span class="kicker">${p[0]} · ${p[1]}</span><h3>${p[2]}</h3><p>${p[3]}</p><a href="#contacto">${l==='en'?'Discuss application':'Conversar aplicación'} →</a></div></article>`).join('')}</div></div>`,'site-section soft');setupReel()}
  function renderContact(l){setHTML('contacto',`<div class="wrap"><div class="contact-box">${sectionHead(l==='en'?'Contact':'Contacto',l==='en'?'Start with a focused conversation':'Empezar con una conversación concreta',l==='en'?'In one short conversation we identify the decision, the areas involved, and the deliverable that would help.':'En una conversación breve identificamos la decisión, las áreas involucradas y el entregable que podría ayudar.')}<a class="btn orange" href="${WHATSAPP}" target="_blank" rel="noopener">${l==='en'?'Schedule conversation by WhatsApp':'Agendar conversación por WhatsApp'}</a><p>${l==='en'?'No long form. A focused first conversation is enough to frame the problem.':'Sin formulario largo. Una primera conversación enfocada alcanza para encuadrar el problema.'}</p></div></div>`,'site-section light')}

  function setupReel(){const sec=document.getElementById('articulos'),track=sec?.querySelector('.paper-reel'),prev=sec?.querySelector('[data-paper-prev]'),next=sec?.querySelector('[data-paper-next]'),cur=sec?.querySelector('.paper-count b'),tot=sec?.querySelector('.paper-count em');if(!track||!prev||!next||!cur||!tot)return;const cards=()=>[...track.querySelectorAll('.paper')];const per=()=>innerWidth<=720?1:(innerWidth<=1050?2:3);const pages=()=>Math.max(1,Math.ceil(cards().length/per()));const idx=()=>{let cs=cards(),b=0,d=1e9;cs.forEach((c,i)=>{let x=Math.abs(c.offsetLeft-track.scrollLeft);if(x<d){d=x;b=i}});return b};const upd=()=>{cur.textContent=Math.min(pages(),Math.floor(idx()/per())+1);tot.textContent=pages()};const mv=n=>{let cs=cards();if(!cs.length)return;let i=Math.max(0,Math.min(cs.length-1,idx()+n*per()));track.scrollTo({left:cs[i].offsetLeft,behavior:'smooth'});setTimeout(upd,250)};prev.onclick=()=>mv(-1);next.onclick=()=>mv(1);track.onscroll=()=>{clearTimeout(track._t);track._t=setTimeout(upd,80)};addEventListener('resize',upd);upd()}

  function modalHTML(kind,id){const l=lang();let obj,title,body;if(kind==='service'){obj=SERVICES.find(x=>x.id===id);if(!obj)return '';let t=obj[l];title=t.title;body=`<p>${esc(t.detail)}</p><h4>${l==='en'?'Leadership receives':'La dirección recibe'}</h4><p>${esc(t.receive)}</p>`}else{obj=CASES.find(x=>x.id===id);if(!obj)return '';let t=obj[l];title=t.title;body=`<p>${esc(t.situation)}</p><div class="mini"><p><strong>${l==='en'?'Decision':'Decisión'}</strong>${esc(t.decision)}</p><p><strong>${l==='en'?'How Praxys works':'Cómo trabaja Praxys'}</strong>${esc(t.work)}</p></div><div class="chips">${t.deliver.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`}return `<div class="modal-box"><button class="close" data-close>×</button>${photo(obj.photo,title)}<div class="modal-content"><span class="kicker">${kind==='service'?(l==='en'?'Service detail':'Detalle del servicio'):(l==='en'?'Case detail':'Detalle del caso')}</span><h2>${esc(title)}</h2>${body}<a class="btn orange" href="${WHATSAPP}" target="_blank" rel="noopener">${l==='en'?'Schedule conversation':'Agendar conversación'}</a></div></div>`}
  function bind(){if(window.PRAXYS&&window.PRAXYS.bound)return;window.PRAXYS=window.PRAXYS||{};window.PRAXYS.bound=true;document.addEventListener('click',e=>{let s=e.target.closest('[data-open-service]'),c=e.target.closest('[data-open-case]'),x=e.target.closest('[data-close]'),m=document.getElementById('px-modal');if(x||e.target===m){m?.classList.remove('open');document.body.classList.remove('lock');return}if(s||c){m=m||document.body.appendChild(Object.assign(document.createElement('div'),{id:'px-modal',className:'modal'}));m.innerHTML=modalHTML(s?'service':'case',s?s.dataset.openService:c.dataset.openCase);m.classList.add('open');document.body.classList.add('lock')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('px-modal')?.classList.remove('open');document.body.classList.remove('lock')}})}
  function render(){installStyles();const l=lang();renderHero(l);renderProblems(l);renderServices(l);renderCTA(l);renderCases(l);renderMethod(l);renderPapers(l);renderContact(l);bind();document.dispatchEvent(new CustomEvent('praxys:rendered',{detail:{lang:l}}))}
  window.PRAXYS=window.PRAXYS||{};window.PRAXYS.refresh=render;document.addEventListener('DOMContentLoaded',render);document.addEventListener('praxys:lang',render);if(document.readyState!=='loading')render();
})();